from fpdf import FPDF

def create_sample_pdf(filename):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    
    # Title
    pdf.cell(200, 10, txt="Advanced AI and Blockchain Integration", ln=True, align='C')
    
    # Content - Paragraph 1
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, txt="\nSection 1: The Role of AI in Intrusion Detection\n"
    "Artificial Intelligence (AI) has revolutionized how we detect network threats. "
    "Unlike traditional signature-based systems, AI-driven Intrusion Detection Systems (IDS) "
    "use Machine Learning models to identify anomalies in traffic patterns. This allows "
    "for the detection of 'Zero-Day' attacks that have no prior signature.")

    # Content - Paragraph 2
    pdf.multi_cell(0, 10, txt="\nSection 2: Decentralized Security via Blockchain\n"
    "Blockchain technology provides a tamper-proof ledger for logging security events. "
    "By integrating blockchain with AI, we ensure that the logs generated by an IDS "
    "cannot be altered by an attacker. This creates a 'Chain of Trust' where the "
    "AI detects the threat and the Blockchain records it immutably.")

    pdf.output(filename)
    print(f"Success! {filename} created.")

create_sample_pdf("study_material.pdf")